version: '3'

services:
  database:
    image: postgres:12.0
    environment:
      POSTGRES_USER: apollo-user
      POSTGRES_PASSWORD: "@pollo"
      POSTGRES_DB: apollo-dev
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - apollo-network
    restart: unless-stopped
  backend:
    build: backend
    networks:
      - apollo-network
    expose:
      - 8081
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - database
    links: 
      - database
  frontend01:
    build: frontend
    networks:
      - apollo-network
    expose:
      - 81
    ports: 
      - 81:8080
    restart: unless-stopped
    depends_on:
      - backend
  frontend02:
    build: frontend
    networks:
      - apollo-network
    expose:
      - 82
    ports: 
      - 82:8080
    restart: unless-stopped
    depends_on:
      - backend
  nginx:
    build: nginx
    networks:
      - apollo-network
    expose:
      - 80
    ports: 
      - 80:80
    restart: unless-stopped
    depends_on:
      - frontend01
      - frontend02
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    networks:
      - apollo-network
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    ports:
        - 5601:5601
    links:
        - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - apollo-network
  logstash:
    image: logstash:7.7.0
    container_name: logstash
    hostname: logstash
    ports:
      - 9600:9600
    volumes:
      - logstash:/usr/share/logstash/pipeline/
    links: 
      - elasticsearch:elasticsearch
    depends_on: 
      - elasticsearch
    networks: 
      - apollo-network
networks: 
  apollo-network:
    driver: bridge

volumes:
  dbdata:
  logstash:
  elasticdata: