version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: apollo-user
      POSTGRES_PASSWORD: "@pollo"
      POSTGRES_DB: apollo-dev
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - apollo-network
    restart: unless-stopped
  backend:
    build: backend
    networks:
      - apollo-network
    expose:
      - 8081
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - database
    links: 
      - database
  frontend:
    build: frontend
    networks:
      - apollo-network
    expose:
      - 80
    ports: 
      - 80:8080
    restart: unless-stopped
    depends_on:
      - backend

networks: 
  apollo-network:
    driver: bridge

volumes:
  dbdata: